# Generated by Django 5.2 on 2025-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', help_text='e.g., per person, per tray, per pack, fixed', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this item currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
