# Generated by Django 5.2 on 2025-05-10 07:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_client_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('delivery_date', models.DateField(help_text='Date of scheduled/actual delivery')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('recipient_name', models.CharField(blank=True, default='', help_text='Name of person receiving the delivery, if different from client contact.', max_length=200)),
                ('delivery_address_override', models.TextField(blank=True, default='', help_text="Specific delivery address for this DO, if different from Order's address.")),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes or instructions for this delivery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='documents.order')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='', help_text='Notes specific to this delivered item (e.g., substitution).')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.deliveryorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivered_items', to='documents.orderitem')),
            ],
            options={
                'verbose_name': 'Delivery Order Item',
                'verbose_name_plural': 'Delivery Order Items',
                'ordering': ['id'],
            },
        ),
    ]
