# Generated by Django 5.2 on 2025-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(choices=[('PERSON', 'Per Person'), ('PACK', 'Per Pack'), ('TRAY', 'Per Tray'), ('ITEM', 'Per Item'), ('FIXED', 'Fixed Price'), ('DAY', 'Per Day'), ('EVENT', 'Per Event'), ('OTHER', 'Other')], default='ITEM', help_text='e.g., per person, per tray, per pack, fixed', max_length=10),
        ),
    ]
