# Generated by Django 5.2 on 2025-05-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_deliveryorder_deliveryorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Credit Note Number')),
                ('issue_date', models.DateField(blank=True, help_text='Date the credit note is officially issued.', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for issuing the credit note.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='documents.client')),
                ('related_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='documents.invoice')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the item/service being credited (can be copied from invoice item or custom).')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the item being credited (usually positive).', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at which the item is being credited (usually matches original invoice price).', max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.creditnote')),
                ('related_invoice_item', models.ForeignKey(blank=True, help_text='Original invoice item this credit applies to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_by_items', to='documents.invoiceitem')),
            ],
            options={
                'verbose_name': 'Credit Note Item',
                'verbose_name_plural': 'Credit Note Items',
                'ordering': ['id'],
            },
        ),
    ]
