# Generated by Django 5.2 on 2025-05-03 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Company Tax ID')),
                ('currency_symbol', models.CharField(default='RM', max_length=5)),
                ('tax_enabled', models.BooleanField(default=False, verbose_name='Enable Tax/SST Calculation')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Enter the rate as a percentage, e.g., 6.00 for 6%', max_digits=5, verbose_name='Tax/SST Rate (%)')),
                ('default_payment_details', models.TextField(blank=True, default='', help_text='Default payment info shown on invoices (e.g., Bank Details)')),
                ('default_terms_conditions', models.TextField(blank=True, default='', help_text='Default terms shown on quotes/invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Application Setting',
            },
        ),
    ]
