# Generated by Django 5.2 on 2025-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Optional company logo.', null=True, upload_to='company_logos/'),
        ),
    ]
