# Generated by Django 5.2 on 2025-05-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_invoice_discount_type_invoice_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_validity_days',
            field=models.PositiveIntegerField(default=15, help_text='Default number of days a quote/invoice is valid from the issue date.'),
        ),
    ]
