# Generated by Django 5.2 on 2025-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_setting_default_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
