# Generated by Django 5.2 on 2025-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_invoice_issue_date_alter_quotation_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
