# Generated by Django 5.2 on 2025-05-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_invoice_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
