# Generated by Django 5.2 on 2025-05-04 04:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_invoice_valid_until_alter_invoice_issue_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, choices=[('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CARD', 'Credit Card'), ('ONLINE', 'Online Payment Gateway'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('reference_number', models.CharField(blank=True, default='', help_text='E.g., Transaction ID, Cheque No.', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='documents.invoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
