# Generated by Django 5.2 on 2025-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Default number of days until an invoice payment is due from the issue date.'),
        ),
    ]
