# Generated by Django 5.2 on 2025-05-04 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_setting_default_payment_terms_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'No Discount'), ('PERCENT', 'Percentage (%)'), ('FIXED', 'Fixed Amount (RM)')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter percentage (e.g., 10.00 for 10%) or fixed amount for overall order discount.', max_digits=10),
        ),
    ]
