# Generated by Django 5.2 on 2025-05-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_order_discount_type_order_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='documents.order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_from_quote', to='documents.quotation'),
        ),
    ]
